services:
  metabolic-log:
    image: ghcr.io/hakovoid/metabolic-log:0.20.0
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - DB_KEY=${DB_KEY}
      - APP_PASSWORD=${APP_PASSWORD}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_URL=${OLLAMA_URL}
    restart: unless-stopped
    x-runtipi:
      is_main: true
      internal_port: 3000

x-runtipi:
  schema_version: 2
